services:
  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - npm_network
    environment:
      - TZ=${TZ}
      - DB_MYSQL_HOST=postgres
      - DB_MYSQL_PORT=5432
      - DB_MYSQL_USER=${NPM_DB_USER}
      - DB_MYSQL_PASSWORD=${NPM_DB_PASSWORD}
      - DB_MYSQL_NAME=${NPM_DB_NAME}
      - DISABLE_IPV6=true
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  netbox:
    container_name: netbox
    image: netboxcommunity/netbox:latest
    ports:
      - "8000:8080"
    environment:
      - ALLOWED_HOSTS=*
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${NETBOX_DB_USER}
      - DB_PASSWORD=${NETBOX_DB_PASSWORD}
      - DB_NAME=${NETBOX_DB_NAME}
      - REDIS_HOST=netbox_redis
      - REDIS_PORT=6379
      - TZ=${TZ}
    volumes:
      - netbox_media:/opt/netbox/netbox/media
      - netbox_static:/opt/netbox/netbox/static
    restart: unless-stopped
    depends_on:
      - postgres
      - netbox_redis
    networks:
      - npm_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "1000:1000"

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_SUPERUSER}
      - POSTGRES_PASSWORD=${POSTGRES_SUPERUSER_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "999:999"

  netbox_redis:
    container_name: netbox_redis
    image: redis:7
    restart: unless-stopped
    networks:
      - npm_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "1000:1000"

volumes:
  npm_data:
  npm_letsencrypt:
  pgdata:
  netbox_media:
  netbox_static:

networks:
  npm_network:
    driver: bridge
