---
- name: Install Docker from official repo and run compose from GitHub
  hosts: all
  become: yes
  vars:
    repo_url: "https://github.com/pantabury/semaphore-video.git"
    repo_dest: "/opt/network-apps"
    repo_dir: "/opt/network-apps/network"

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone or update repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: main
        update: yes

    - name: Run docker compose up
      community.docker.docker_compose_v2:
        project_src: "{{ repo_dir }}"
        state: present
