services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: "${TZ}"
      WEBPASSWORD: "${WEBPASSWORD}"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
