---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: "Europe/London"
      WEBPASSWORD: "tesco"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80" # Pi-hole web UI
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"  # NPM admin UI
      - "443:443"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    hostname: lan-proxy
    volumes:
      - ./tailscale:/var/lib/tailscale
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    command: tailscaled
