CREATE DATABASE npm_db;
CREATE USER npm WITH ENCRYPTED PASSWORD 'Ca53yjn2219';
GRANT ALL PRIVILEGES ON DATABASE npm_db TO npm;

CREATE DATABASE netbox_db;
CREATE USER netbox WITH ENCRYPTED PASSWORD 'Ca53yjn2219';
GRANT ALL PRIVILEGES ON DATABASE netbox_db TO netbox;
